services:
  backend:
    build:
      context: fastapi_backend
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:password@db:5432/awesome_docify
      - QDRANT_PATH=/app/local-shared-data/qdrant
      - DOCUMENT_LOADER_DIR=/app/local-shared-data/docs
    ports:
      - "8000:8000"
    networks:
      - my_network
    volumes:
      - ./fastapi_backend:/app
      - ./local-shared-data:/app/local-shared-data
    depends_on:
      - db

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: awesome_docify
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - ./local-shared-data/postgres:/var/lib/postgresql/data

  frontend:
    build:
      context: ./nextjs-frontend
    user: node
    ports:
      - "3000:3000"
    networks:
      - my_network
    env_file:
      - .env
    environment:
      NODE_ENV: development
      API_BASE_URL: http://backend:8000
      NEXT_PUBLIC_API_BASE_URL: http://backend:8000
    volumes:
      - ./nextjs-frontend:/app
      - nextjs-node-modules:/app/node_modules

volumes:
  nextjs-node-modules:

networks:
  my_network:
    driver: bridge
