version: "3.8"

services:
  backend:
    build:
      context: fastapi_backend
    environment:
      - OPENAPI_OUTPUT_FILE=./shared-data/openapi.json
      - DATABASE_URL=postgresql+asyncpg://postgres:password@db:5432/awesome_docify
    ports:
      - "8000:8000"
    networks:
      - my_network
    volumes:
      - ./fastapi_backend:/app
      - ./local-shared-data:/app/shared-data
    depends_on:
      - db
      - qdrant

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: awesome_docify
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - ./local-shared-data/postgres:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    networks:
      - my_network
    volumes:
      - ./local-shared-data/qdrant:/qdrant/storage

  frontend:
    build:
      context: ./nextjs-frontend
    user: node
    ports:
      - "3000:3000"
    networks:
      - my_network
    environment:
      NODE_ENV: development
      API_BASE_URL: http://backend:8000
      OPENAPI_OUTPUT_FILE: ./shared-data/openapi.json
    volumes:
      - ./nextjs-frontend:/app
      - nextjs-node-modules:/app/node_modules
      - ./local-shared-data:/app/shared-data

volumes:
  nextjs-node-modules:

networks:
  my_network:
    driver: bridge
